#!/usr/bin/env python3
"""Generate the runtime data_config yaml consumed by robotera_vla training.

Takes explicit LeRobot collection paths (--repo, one per wired upstream
dataset port; each must contain meta/ and data/) and writes a yaml
structurally identical to training/configs/data_config_260322.yml, with
repo_id_list pointing at the absolute local paths. The upstream project is
never modified: the generated file overwrites the copy inside the thin
runtime workdir. There is no directory-scanning fallback: datasets can only
enter via port wiring.
"""
import argparse
import pathlib
import sys

TEMPLATE = """\
# generated by operator/adapters/gen_data_config.py at runtime
{task_key}:
  type: "LeRobotM7DataConfig"
  weight: 1.0
  repo_id_list:
{repo_lines}
  action_sequence_keys: ["action"]
  repack_transforms:
    images:
      cam_high: "observation.images.cam_high"
      cam_left_wrist: "observation.images.cam_left"
      cam_right_wrist: "observation.images.cam_right"
    state: "observation.state"
    actions: "action"
    prompt: "prompt"
  base_config:
     prompt_from_task: true
"""


def is_lerobot_collection(path: pathlib.Path) -> bool:
    return (path / "meta").is_dir() and (path / "data").is_dir()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--repo",
        action="append",
        required=True,
        help="explicit LeRobot collection path; repeatable, wired from upstream ports",
    )
    parser.add_argument("--out", required=True)
    parser.add_argument("--task-key", default="m7_good2people")
    args = parser.parse_args()

    repos = [str(pathlib.Path(r).resolve()) for r in args.repo]
    for repo in repos:
        if not is_lerobot_collection(pathlib.Path(repo)):
            print(f"ERROR: --repo is not a LeRobot collection (needs meta/ + data/): {repo}", file=sys.stderr)
            return 1

    repo_lines = "\n".join(f'    - "{repo}"' for repo in repos)
    payload = TEMPLATE.format(task_key=args.task_key, repo_lines=repo_lines)

    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(payload)
    print(f"[gen_data_config] wrote {out} with {len(repos)} repo(s):")
    for repo in repos:
        print(f"[gen_data_config]   {repo}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
